# Generated by Django 5.2.7 on 2025-10-30 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={"verbose_name": "Раздел", "verbose_name_plural": "Разделы"},
        ),
        migrations.RemoveField(
            model_name="material",
            name="course",
        ),
        migrations.AddField(
            model_name="material",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите раздел",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.section",
                verbose_name="Раздел",
            ),
        ),
    ]
