# Generated by Django 4.2.2 on 2025-11-01 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_section_options_remove_material_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание материала"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название материала"),
        ),
        migrations.AlterField(
            model_name="material",
            name="section",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.section",
                verbose_name="Раздел",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание раздела"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название раздела"),
        ),
    ]
