# Generated by Django 5.2.7 on 2025-11-01 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_material_description_alter_material_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.section",
                verbose_name="Раздел",
            ),
        ),
    ]
