# Generated by Django 4.2.2 on 2025-11-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_material_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="materials.section",
                verbose_name="Раздел",
            ),
        ),
    ]
