# Generated by Django 5.2.7 on 2025-11-02 16:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_answer_student_question_owner_alter_answer_question_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testresult",
            old_name="answers",
            new_name="answers_data",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="student",
        ),
        migrations.RemoveField(
            model_name="testresult",
            name="question",
        ),
        migrations.AddField(
            model_name="testresult",
            name="completed_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 2, 16, 31, 4, 990411, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testresult",
            name="correct_answers",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Правильных ответов"
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="is_passed",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Тест пройден"
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="percentage",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Процент правильных ответов"
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="score",
            field=models.IntegerField(blank=True, null=True, verbose_name="Баллы"),
        ),
        migrations.AddField(
            model_name="testresult",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tests.test",
                verbose_name="Тест",
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="total_questions",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Всего вопросов"
            ),
        ),
    ]
