# Generated by Django 5.2.7 on 2025-11-02 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0003_rename_answers_testresult_answers_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="tests.test",
                verbose_name="Тест",
            ),
        ),
    ]
