# Generated by Django 5.2.7 on 2025-11-02 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_material_section"),
        ("tests", "0004_alter_question_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="materials.material",
                verbose_name="Материал",
            ),
        ),
    ]
