# Generated by Django 5.2.7 on 2025-11-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0006_alter_answer_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testresult",
            name="answers_data",
        ),
    ]
